<?php
declare(strict_types=1);

namespace JDWil\PhpGenny\Builder\Node;

use JDWil\PhpGenny\Builder\Node\Traits\InternalFunctionTrait;

/**
 * Trait InternalFunctionTrait
 *
 * @method static zend_version()
 * @method static func_num_args()
 * @method static func_get_arg($arg_num)
 * @method static func_get_args()
 * @method static strlen($str)
 * @method static strcmp($str1, $str2)
 * @method static strncmp($str1, $str2, $len)
 * @method static strcasecmp($str1, $str2)
 * @method static strncasecmp($str1, $str2, $len)
 * @method static each($arr)
 * @method static error_reporting($new_error_level)
 * @method static define($constant_name, $value, $case_insensitive)
 * @method static defined($constant_name)
 * @method static get_class($object)
 * @method static get_called_class()
 * @method static get_parent_class($object)
 * @method static method_exists($object, $method)
 * @method static property_exists($object_or_class, $property_name)
 * @method static class_exists($classname, $autoload)
 * @method static interface_exists($classname, $autoload)
 * @method static trait_exists($traitname, $autoload)
 * @method static function_exists($function_name)
 * @method static class_alias($user_class_name, $alias_name, $autoload)
 * @method static get_included_files()
 * @method static get_required_files()
 * @method static is_subclass_of($object, $class_name, $allow_string)
 * @method static is_a($object, $class_name, $allow_string)
 * @method static get_class_vars($class_name)
 * @method static get_object_vars($obj)
 * @method static get_class_methods($class)
 * @method static trigger_error($message, $error_type)
 * @method static user_error($message, $error_type)
 * @method static set_error_handler($error_handler, $error_types)
 * @method static restore_error_handler()
 * @method static set_exception_handler($exception_handler)
 * @method static restore_exception_handler()
 * @method static get_declared_classes()
 * @method static get_declared_traits()
 * @method static get_declared_interfaces()
 * @method static get_defined_functions()
 * @method static get_defined_vars()
 * @method static create_function($args, $code)
 * @method static get_resource_type($res)
 * @method static get_resources($type)
 * @method static get_loaded_extensions($zend_extensions)
 * @method static extension_loaded($extension_name)
 * @method static get_extension_funcs($extension_name)
 * @method static get_defined_constants($categorize)
 * @method static debug_backtrace($options, $limit)
 * @method static debug_print_backtrace($options, $limit)
 * @method static gc_mem_caches()
 * @method static gc_collect_cycles()
 * @method static gc_enabled()
 * @method static gc_enable()
 * @method static gc_disable()
 * @method static strtotime($time, $now)
 * @method static date($format, $timestamp)
 * @method static idate($format, $timestamp)
 * @method static gmdate($format, $timestamp)
 * @method static mktime($hour, $min, $sec, $mon, $day, $year)
 * @method static gmmktime($hour, $min, $sec, $mon, $day, $year)
 * @method static checkdate($month, $day, $year)
 * @method static strftime($format, $timestamp)
 * @method static gmstrftime($format, $timestamp)
 * @method static time()
 * @method static localtime($timestamp, $associative_array)
 * @method static getdate($timestamp)
 * @method static date_create($time, $object)
 * @method static date_create_immutable($time, $object)
 * @method static date_create_from_format($format, $time, $object)
 * @method static date_create_immutable_from_format($format, $time, $object)
 * @method static date_parse($date)
 * @method static date_parse_from_format($format, $date)
 * @method static date_get_last_errors()
 * @method static date_format($object, $format)
 * @method static date_modify($object, $modify)
 * @method static date_add($object, $interval)
 * @method static date_sub($object, $interval)
 * @method static date_timezone_get($object)
 * @method static date_timezone_set($object, $timezone)
 * @method static date_offset_get($object)
 * @method static date_diff($object, $object2, $absolute)
 * @method static date_time_set($object, $hour, $minute, $second, $microseconds)
 * @method static date_date_set($object, $year, $month, $day)
 * @method static date_isodate_set($object, $year, $week, $day)
 * @method static date_timestamp_set($object, $unixtimestamp)
 * @method static date_timestamp_get($object)
 * @method static timezone_open($timezone)
 * @method static timezone_name_get($object)
 * @method static timezone_name_from_abbr($abbr, $gmtoffset, $isdst)
 * @method static timezone_offset_get($object, $datetime)
 * @method static timezone_transitions_get($object, $timestamp_begin, $timestamp_end)
 * @method static timezone_location_get($object)
 * @method static timezone_identifiers_list($what, $country)
 * @method static timezone_abbreviations_list()
 * @method static timezone_version_get()
 * @method static date_interval_create_from_date_string($time)
 * @method static date_interval_format($object, $format)
 * @method static date_default_timezone_set($timezone_identifier)
 * @method static date_default_timezone_get()
 * @method static date_sunrise($time, $format, $latitude, $longitude, $zenith, $gmt_offset)
 * @method static date_sunset($time, $format, $latitude, $longitude, $zenith, $gmt_offset)
 * @method static date_sun_info($time, $latitude, $longitude)
 * @method static libxml_set_streams_context($context)
 * @method static libxml_use_internal_errors($use_errors)
 * @method static libxml_get_last_error()
 * @method static libxml_clear_errors()
 * @method static libxml_get_errors()
 * @method static libxml_disable_entity_loader($disable)
 * @method static libxml_set_external_entity_loader($resolver_function)
 * @method static openssl_get_cert_locations()
 * @method static openssl_spki_new($privkey, $challenge, $algo)
 * @method static openssl_spki_verify($spki)
 * @method static openssl_spki_export($spki)
 * @method static openssl_spki_export_challenge($spki)
 * @method static openssl_pkey_free($key)
 * @method static openssl_pkey_new($configargs)
 * @method static openssl_pkey_export($key, $out, $passphrase, $config_args)
 * @method static openssl_pkey_export_to_file($key, $outfilename, $passphrase, $config_args)
 * @method static openssl_pkey_get_private($key, $passphrase)
 * @method static openssl_pkey_get_public($cert)
 * @method static openssl_pkey_get_details($key)
 * @method static openssl_free_key($key)
 * @method static openssl_get_privatekey($key, $passphrase)
 * @method static openssl_get_publickey($cert)
 * @method static openssl_x509_read($cert)
 * @method static openssl_x509_free($x509)
 * @method static openssl_x509_parse($x509, $shortname)
 * @method static openssl_x509_checkpurpose($x509cert, $purpose, $cainfo, $untrustedfile)
 * @method static openssl_x509_check_private_key($cert, $key)
 * @method static openssl_x509_export($x509, $out, $notext)
 * @method static openssl_x509_fingerprint($x509, $method, $raw_output)
 * @method static openssl_x509_export_to_file($x509, $outfilename, $notext)
 * @method static openssl_pkcs12_export($x509, $out, $priv_key, $pass, $args)
 * @method static openssl_pkcs12_export_to_file($x509, $filename, $priv_key, $pass, $args)
 * @method static openssl_pkcs12_read($PKCS12, $certs, $pass)
 * @method static openssl_csr_new($dn, $privkey, $configargs, $extraattribs)
 * @method static openssl_csr_export($csr, $out, $notext)
 * @method static openssl_csr_export_to_file($csr, $outfilename, $notext)
 * @method static openssl_csr_sign($csr, $x509, $priv_key, $days, $config_args, $serial)
 * @method static openssl_csr_get_subject($csr)
 * @method static openssl_csr_get_public_key($csr)
 * @method static openssl_digest($data, $method, $raw_output)
 * @method static openssl_encrypt($data, $method, $password, $options, $iv, $tag, $aad, $tag_length)
 * @method static openssl_decrypt($data, $method, $password, $options, $iv, $tag, $aad)
 * @method static openssl_cipher_iv_length($method)
 * @method static openssl_sign($data, $signature, $key, $method)
 * @method static openssl_verify($data, $signature, $key, $method)
 * @method static openssl_seal($data, $sealdata, $ekeys, $pubkeys, $method, $iv)
 * @method static openssl_open($data, $opendata, $ekey, $privkey, $iv)
 * @method static openssl_pbkdf2($password, $salt, $key_length, $iterations, $digest_algorithm)
 * @method static openssl_pkcs7_verify($filename, $flags, $signerscerts, $cainfo, $extracerts, $content)
 * @method static openssl_pkcs7_decrypt($infilename, $outfilename, $recipcert, $recipkey)
 * @method static openssl_pkcs7_sign($infile, $outfile, $signcert, $signkey, $headers, $flags, $extracertsfilename)
 * @method static openssl_pkcs7_encrypt($infile, $outfile, $recipcerts, $headers, $flags, $cipher)
 * @method static openssl_private_encrypt($data, $crypted, $key, $padding)
 * @method static openssl_private_decrypt($data, $crypted, $key, $padding)
 * @method static openssl_public_encrypt($data, $crypted, $key, $padding)
 * @method static openssl_public_decrypt($data, $crypted, $key, $padding)
 * @method static openssl_get_md_methods($aliases)
 * @method static openssl_get_cipher_methods($aliases)
 * @method static openssl_get_curve_names()
 * @method static openssl_dh_compute_key($pub_key, $dh_key)
 * @method static openssl_random_pseudo_bytes($length, $result_is_strong)
 * @method static openssl_error_string()
 * @method static preg_match($pattern, $subject, $subpatterns, $flags, $offset)
 * @method static preg_match_all($pattern, $subject, $subpatterns, $flags, $offset)
 * @method static preg_replace($regex, $replace, $subject, $limit, $count)
 * @method static preg_replace_callback($regex, $callback, $subject, $limit, $count)
 * @method static preg_replace_callback_array($pattern, $subject, $limit, $count)
 * @method static preg_filter($regex, $replace, $subject, $limit, $count)
 * @method static preg_split($pattern, $subject, $limit, $flags)
 * @method static preg_quote($str, $delim_char)
 * @method static preg_grep($regex, $input, $flags)
 * @method static preg_last_error()
 * @method static readgzfile($filename, $use_include_path)
 * @method static gzrewind($fp)
 * @method static gzclose($fp)
 * @method static gzeof($fp)
 * @method static gzgetc($fp)
 * @method static gzgets($fp, $length)
 * @method static gzgetss($fp, $length, $allowable_tags)
 * @method static gzread($fp, $length)
 * @method static gzopen($filename, $mode, $use_include_path)
 * @method static gzpassthru($fp)
 * @method static gzseek($fp, $offset, $whence)
 * @method static gztell($fp)
 * @method static gzwrite($fp, $str, $length)
 * @method static gzputs($fp, $str, $length)
 * @method static gzfile($filename, $use_include_path)
 * @method static gzcompress($data, $level, $encoding)
 * @method static gzuncompress($data, $max_decoded_len)
 * @method static gzdeflate($data, $level, $encoding)
 * @method static gzinflate($data, $max_decoded_len)
 * @method static gzencode($data, $level, $encoding)
 * @method static gzdecode($data, $max_decoded_len)
 * @method static zlib_encode($data, $encoding, $level)
 * @method static zlib_decode($data, $max_decoded_len)
 * @method static zlib_get_coding_type()
 * @method static deflate_init($encoding, $level)
 * @method static deflate_add($resource, $add, $flush_behavior)
 * @method static inflate_init($encoding)
 * @method static inflate_add($resource, $flush_behavior)
 * @method static ob_gzhandler($data, $flags)
 * @method static filter_input($type, $variable_name, $filter, $options)
 * @method static filter_var($variable, $filter, $options)
 * @method static filter_input_array($type, $definition, $add_empty)
 * @method static filter_var_array($data, $definition, $add_empty)
 * @method static filter_list()
 * @method static filter_has_var($type, $variable_name)
 * @method static filter_id($filtername)
 * @method static hash($algo, $data, $raw_output)
 * @method static hash_file($algo, $filename, $raw_output)
 * @method static hash_hmac($algo, $data, $key, $raw_output)
 * @method static hash_hmac_file($algo, $filename, $key, $raw_output)
 * @method static hash_init($algo, $options, $key)
 * @method static hash_update($context, $data)
 * @method static hash_update_stream($context, $handle, $length)
 * @method static hash_update_file($context, $filename, $context)
 * @method static hash_final($context, $raw_output)
 * @method static hash_copy($context)
 * @method static hash_algos()
 * @method static hash_pbkdf2($algo, $password, $salt, $iterations, $length, $raw_output)
 * @method static hash_equals($known_string, $user_string)
 * @method static hash_hkdf($ikm, $algo, $length, $string, $salt)
 * @method static mhash_keygen_s2k($hash, $input_password, $salt, $bytes)
 * @method static mhash_get_block_size($hash)
 * @method static mhash_get_hash_name($hash)
 * @method static mhash_count()
 * @method static mhash($hash, $data, $key)
 * @method static pcntl_fork()
 * @method static pcntl_waitpid($pid, $status, $options, $rusage)
 * @method static pcntl_wait($status, $options, $rusage)
 * @method static pcntl_signal($signo, $handler, $restart_syscalls)
 * @method static pcntl_signal_get_handler($signo)
 * @method static pcntl_signal_dispatch()
 * @method static pcntl_wifexited($status)
 * @method static pcntl_wifstopped($status)
 * @method static pcntl_wifsignaled($status)
 * @method static pcntl_wexitstatus($status)
 * @method static pcntl_wtermsig($status)
 * @method static pcntl_wstopsig($status)
 * @method static pcntl_exec($path, $args, $envs)
 * @method static pcntl_alarm($seconds)
 * @method static pcntl_get_last_error()
 * @method static pcntl_errno()
 * @method static pcntl_strerror($errno)
 * @method static pcntl_getpriority($pid, $process_identifier)
 * @method static pcntl_setpriority($priority, $pid, $process_identifier)
 * @method static pcntl_sigprocmask($how, $set, $oldset)
 * @method static pcntl_sigwaitinfo($set, $info)
 * @method static pcntl_sigtimedwait($set, $info, $seconds, $nanoseconds)
 * @method static pcntl_wifcontinued($status)
 * @method static pcntl_async_signals($on)
 * @method static session_name($name)
 * @method static session_module_name($module)
 * @method static session_save_path($path)
 * @method static session_id($id)
 * @method static session_create_id($prefix)
 * @method static session_regenerate_id($delete_old_session)
 * @method static session_decode($data)
 * @method static session_encode()
 * @method static session_start($options)
 * @method static session_destroy()
 * @method static session_unset()
 * @method static session_gc()
 * @method static session_set_save_handler($open, $close, $read, $write, $destroy, $gc, $create_sid, $validate_sid, $update_timestamp)
 * @method static session_cache_limiter($cache_limiter)
 * @method static session_cache_expire($new_cache_expire)
 * @method static session_set_cookie_params($lifetime, $path, $domain, $secure, $httponly)
 * @method static session_get_cookie_params()
 * @method static session_write_close()
 * @method static session_abort()
 * @method static session_reset()
 * @method static session_status()
 * @method static session_register_shutdown()
 * @method static session_commit()
 * @method static spl_classes()
 * @method static spl_autoload($class_name, $file_extensions)
 * @method static spl_autoload_extensions($file_extensions)
 * @method static spl_autoload_register($autoload_function, $throw, $prepend)
 * @method static spl_autoload_unregister($autoload_function)
 * @method static spl_autoload_functions()
 * @method static spl_autoload_call($class_name)
 * @method static class_parents($instance, $autoload)
 * @method static class_implements($what, $autoload)
 * @method static class_uses($what, $autoload)
 * @method static spl_object_hash($obj)
 * @method static iterator_to_array($iterator, $use_keys)
 * @method static iterator_count($iterator)
 * @method static iterator_apply($iterator, $function, $args)
 * @method static constant($const_name)
 * @method static bin2hex($data)
 * @method static hex2bin($data)
 * @method static sleep($seconds)
 * @method static usleep($micro_seconds)
 * @method static time_nanosleep($seconds, $nanoseconds)
 * @method static time_sleep_until($timestamp)
 * @method static strptime($timestamp, $format)
 * @method static flush()
 * @method static wordwrap($str, $width, $break, $cut)
 * @method static htmlspecialchars($string, $quote_style, $encoding, $double_encode)
 * @method static htmlentities($string, $quote_style, $encoding, $double_encode)
 * @method static html_entity_decode($string, $quote_style, $encoding)
 * @method static htmlspecialchars_decode($string, $quote_style)
 * @method static get_html_translation_table($table, $quote_style, $encoding)
 * @method static sha1($str, $raw_output)
 * @method static sha1_file($filename, $raw_output)
 * @method static md5($str, $raw_output)
 * @method static md5_file($filename, $raw_output)
 * @method static crc32($str)
 * @method static iptcparse($iptcdata)
 * @method static iptcembed($iptcdata, $jpeg_file_name, $spool)
 * @method static getimagesize($imagefile, $info)
 * @method static getimagesizefromstring($imagefile, $info)
 * @method static image_type_to_mime_type($imagetype)
 * @method static image_type_to_extension($imagetype, $include_dot)
 * @method static phpinfo($what)
 * @method static phpversion($extension)
 * @method static phpcredits($flag)
 * @method static php_sapi_name()
 * @method static php_uname($mode)
 * @method static php_ini_scanned_files()
 * @method static php_ini_loaded_file()
 * @method static strnatcmp($s1, $s2)
 * @method static strnatcasecmp($s1, $s2)
 * @method static substr_count($haystack, $needle, $offset, $length)
 * @method static strspn($str, $mask, $start, $len)
 * @method static strcspn($str, $mask, $start, $len)
 * @method static strtok($str, $token)
 * @method static strtoupper($str)
 * @method static strtolower($str)
 * @method static strpos($haystack, $needle, $offset)
 * @method static stripos($haystack, $needle, $offset)
 * @method static strrpos($haystack, $needle, $offset)
 * @method static strripos($haystack, $needle, $offset)
 * @method static strrev($str)
 * @method static hebrev($str, $max_chars_per_line)
 * @method static hebrevc($str, $max_chars_per_line)
 * @method static nl2br($str, $is_xhtml)
 * @method static basename($path, $suffix)
 * @method static dirname($path, $levels)
 * @method static pathinfo($path, $options)
 * @method static stripslashes($str)
 * @method static stripcslashes($str)
 * @method static strstr($haystack, $needle, $part)
 * @method static stristr($haystack, $needle, $part)
 * @method static strrchr($haystack, $needle)
 * @method static str_shuffle($str)
 * @method static str_word_count($str, $format, $charlist)
 * @method static str_split($str, $split_length)
 * @method static strpbrk($haystack, $char_list)
 * @method static substr_compare($main_str, $str, $offset, $length, $case_sensitivity)
 * @method static strcoll($str1, $str2)
 * @method static money_format($format, $value)
 * @method static substr($str, $start, $length)
 * @method static substr_replace($str, $replace, $start, $length)
 * @method static quotemeta($str)
 * @method static ucfirst($str)
 * @method static lcfirst($str)
 * @method static ucwords($str, $delimiters)
 * @method static strtr($str, $from, $to)
 * @method static addslashes($str)
 * @method static addcslashes($str, $charlist)
 * @method static rtrim($str, $character_mask)
 * @method static str_replace($search, $replace, $subject, $replace_count)
 * @method static str_ireplace($search, $replace, $subject, $replace_count)
 * @method static str_repeat($input, $mult)
 * @method static count_chars($input, $mode)
 * @method static chunk_split($str, $chunklen, $ending)
 * @method static trim($str, $character_mask)
 * @method static ltrim($str, $character_mask)
 * @method static strip_tags($str, $allowable_tags)
 * @method static similar_text($str1, $str2, $percent)
 * @method static explode($separator, $str, $limit)
 * @method static implode($glue, $pieces)
 * @method static join($glue, $pieces)
 * @method static setlocale($category, $locales)
 * @method static localeconv()
 * @method static nl_langinfo($item)
 * @method static soundex($str)
 * @method static levenshtein($str1, $str2, $cost_ins, $cost_rep, $cost_del)
 * @method static chr($codepoint)
 * @method static ord($character)
 * @method static parse_str($encoded_string, $result)
 * @method static str_getcsv($string, $delimiter, $enclosure, $escape)
 * @method static str_pad($input, $pad_length, $pad_string, $pad_type)
 * @method static chop($str, $character_mask)
 * @method static strchr($haystack, $needle, $part)
 * @method static sprintf($format, $args)
 * @method static printf($format, $args)
 * @method static vprintf($format, $args)
 * @method static vsprintf($format, $args)
 * @method static fprintf($stream, $format, $args)
 * @method static vfprintf($stream, $format, $args)
 * @method static sscanf($str, $format, $vars)
 * @method static fscanf($stream, $format, $vars)
 * @method static parse_url($url, $component)
 * @method static urlencode($str)
 * @method static urldecode($str)
 * @method static rawurlencode($str)
 * @method static rawurldecode($str)
 * @method static http_build_query($formdata, $prefix, $arg_separator, $enc_type)
 * @method static readlink($filename)
 * @method static linkinfo($filename)
 * @method static symlink($target, $link)
 * @method static link($target, $link)
 * @method static unlink($filename, $context)
 * @method static exec($command, $output, $return_value)
 * @method static system($command, $return_value)
 * @method static escapeshellcmd($command)
 * @method static escapeshellarg($arg)
 * @method static passthru($command, $return_value)
 * @method static shell_exec($cmd)
 * @method static proc_open($command, $descriptorspec, $pipes, $cwd, $env, $other_options)
 * @method static proc_close($process)
 * @method static proc_terminate($process, $signal)
 * @method static proc_get_status($process)
 * @method static proc_nice($priority)
 * @method static rand($min, $max)
 * @method static srand($seed, $mode)
 * @method static getrandmax()
 * @method static mt_rand($min, $max)
 * @method static mt_srand($seed, $mode)
 * @method static mt_getrandmax()
 * @method static random_bytes($length)
 * @method static random_int($min, $max)
 * @method static getservbyname($service, $protocol)
 * @method static getservbyport($port, $protocol)
 * @method static getprotobyname($name)
 * @method static getprotobynumber($proto)
 * @method static getmyuid()
 * @method static getmygid()
 * @method static getmypid()
 * @method static getmyinode()
 * @method static getlastmod()
 * @method static base64_decode($str, $strict)
 * @method static base64_encode($str)
 * @method static password_hash($password, $algo, $options)
 * @method static password_get_info($hash)
 * @method static password_needs_rehash($hash, $algo, $options)
 * @method static password_verify($password, $hash)
 * @method static convert_uuencode($data)
 * @method static convert_uudecode($data)
 * @method static abs($number)
 * @method static ceil($number)
 * @method static floor($number)
 * @method static round($number, $precision, $mode)
 * @method static sin($number)
 * @method static cos($number)
 * @method static tan($number)
 * @method static asin($number)
 * @method static acos($number)
 * @method static atan($number)
 * @method static atanh($number)
 * @method static atan2($y, $x)
 * @method static sinh($number)
 * @method static cosh($number)
 * @method static tanh($number)
 * @method static asinh($number)
 * @method static acosh($number)
 * @method static expm1($number)
 * @method static log1p($number)
 * @method static pi()
 * @method static is_finite($val)
 * @method static is_nan($val)
 * @method static is_infinite($val)
 * @method static pow($base, $exponent)
 * @method static exp($number)
 * @method static log($number, $base)
 * @method static log10($number)
 * @method static sqrt($number)
 * @method static hypot($num1, $num2)
 * @method static deg2rad($number)
 * @method static rad2deg($number)
 * @method static bindec($binary_number)
 * @method static hexdec($hexadecimal_number)
 * @method static octdec($octal_number)
 * @method static decbin($decimal_number)
 * @method static decoct($decimal_number)
 * @method static dechex($decimal_number)
 * @method static base_convert($number, $frombase, $tobase)
 * @method static number_format($number, $num_decimal_places, $dec_separator, $thousands_separator)
 * @method static fmod($x, $y)
 * @method static intdiv($dividend, $divisor)
 * @method static inet_ntop($in_addr)
 * @method static inet_pton($ip_address)
 * @method static ip2long($ip_address)
 * @method static long2ip($proper_address)
 * @method static getenv($varname, $local_only)
 * @method static putenv($setting)
 * @method static getopt($options, $opts, $optind)
 * @method static sys_getloadavg()
 * @method static microtime($get_as_float)
 * @method static gettimeofday($get_as_float)
 * @method static getrusage($who)
 * @method static uniqid($prefix, $more_entropy)
 * @method static quoted_printable_decode($str)
 * @method static quoted_printable_encode($str)
 * @method static convert_cyr_string($str, $from, $to)
 * @method static get_current_user()
 * @method static set_time_limit($seconds)
 * @method static header_register_callback($callback)
 * @method static get_cfg_var($option_name)
 * @method static get_magic_quotes_gpc()
 * @method static get_magic_quotes_runtime()
 * @method static error_log($message, $message_type, $destination, $extra_headers)
 * @method static error_get_last()
 * @method static error_clear_last()
 * @method static call_user_func($function_name, $parameters)
 * @method static call_user_func_array($function_name, $parameters)
 * @method static forward_static_call($function_name, $parameters)
 * @method static forward_static_call_array($function_name, $parameters)
 * @method static serialize($var)
 * @method static unserialize($variable_representation, $allowed_classes)
 * @method static var_dump($vars)
 * @method static var_export($var, $return)
 * @method static debug_zval_dump($vars)
 * @method static print_r($var, $return)
 * @method static memory_get_usage($real_usage)
 * @method static memory_get_peak_usage($real_usage)
 * @method static register_shutdown_function($function_name, $parameters)
 * @method static register_tick_function($function_name, $parameters)
 * @method static unregister_tick_function($function_name)
 * @method static highlight_file($file_name, $return)
 * @method static show_source($file_name, $return)
 * @method static highlight_string($string, $return)
 * @method static php_strip_whitespace($file_name)
 * @method static ini_get($varname)
 * @method static ini_get_all($extension, $details)
 * @method static ini_set($varname, $newvalue)
 * @method static ini_alter($varname, $newvalue)
 * @method static ini_restore($varname)
 * @method static get_include_path()
 * @method static set_include_path($new_include_path)
 * @method static restore_include_path()
 * @method static setcookie($name, $value, $expires, $path, $domain, $secure, $httponly)
 * @method static setrawcookie($name, $value, $expires, $path, $domain, $secure, $httponly)
 * @method static header($header, $replace, $http_response_code)
 * @method static header_remove($name)
 * @method static headers_sent($file, $line)
 * @method static headers_list()
 * @method static http_response_code($response_code)
 * @method static connection_aborted()
 * @method static connection_status()
 * @method static ignore_user_abort($value)
 * @method static parse_ini_file($filename, $process_sections, $scanner_mode)
 * @method static parse_ini_string($ini_string, $process_sections, $scanner_mode)
 * @method static is_uploaded_file($path)
 * @method static move_uploaded_file($path, $new_path)
 * @method static gethostbyaddr($ip_address)
 * @method static gethostbyname($hostname)
 * @method static gethostbynamel($hostname)
 * @method static gethostname()
 * @method static dns_check_record($host, $type)
 * @method static checkdnsrr($host, $type)
 * @method static dns_get_mx($hostname, $mxhosts, $weight)
 * @method static getmxrr($hostname, $mxhosts, $weight)
 * @method static dns_get_record($hostname, $type, $authns, $addtl, $raw)
 * @method static intval($var, $base)
 * @method static floatval($var)
 * @method static doubleval($var)
 * @method static strval($var)
 * @method static boolval($var)
 * @method static gettype($var)
 * @method static settype($var, $type)
 * @method static is_null($var)
 * @method static is_resource($var)
 * @method static is_bool($var)
 * @method static is_int($var)
 * @method static is_float($var)
 * @method static is_integer($var)
 * @method static is_long($var)
 * @method static is_double($var)
 * @method static is_real($var)
 * @method static is_numeric($value)
 * @method static is_string($var)
 * @method static is_array($var)
 * @method static is_object($var)
 * @method static is_scalar($value)
 * @method static is_callable($var, $syntax_only, $callable_name)
 * @method static is_iterable($var)
 * @method static pclose($fp)
 * @method static popen($command, $mode)
 * @method static readfile($filename, $flags, $context)
 * @method static rewind($fp)
 * @method static rmdir($dirname, $context)
 * @method static umask($mask)
 * @method static fclose($fp)
 * @method static feof($fp)
 * @method static fgetc($fp)
 * @method static fgets($fp, $length)
 * @method static fgetss($fp, $length, $allowable_tags)
 * @method static fread($fp, $length)
 * @method static fopen($filename, $mode, $use_include_path, $context)
 * @method static fpassthru($fp)
 * @method static ftruncate($fp, $size)
 * @method static fstat($fp)
 * @method static fseek($fp, $offset, $whence)
 * @method static ftell($fp)
 * @method static fflush($fp)
 * @method static fwrite($fp, $str, $length)
 * @method static fputs($fp, $str, $length)
 * @method static mkdir($pathname, $mode, $recursive, $context)
 * @method static rename($old_name, $new_name, $context)
 * @method static copy($source_file, $destination_file, $context)
 * @method static tempnam($dir, $prefix)
 * @method static tmpfile()
 * @method static file($filename, $flags, $context)
 * @method static file_get_contents($filename, $flags, $context, $offset, $maxlen)
 * @method static file_put_contents($filename, $data, $flags, $context)
 * @method static stream_select($read_streams, $write_streams, $except_streams, $tv_sec, $tv_usec)
 * @method static stream_context_create($options, $params)
 * @method static stream_context_set_params($stream_or_context, $options)
 * @method static stream_context_get_params($stream_or_context)
 * @method static stream_context_set_option($stream_or_context, $wrappername, $optionname, $value)
 * @method static stream_context_get_options($stream_or_context)
 * @method static stream_context_get_default($options)
 * @method static stream_context_set_default($options)
 * @method static stream_filter_prepend($stream, $filtername, $read_write, $filterparams)
 * @method static stream_filter_append($stream, $filtername, $read_write, $filterparams)
 * @method static stream_filter_remove($stream_filter)
 * @method static stream_socket_client($remoteaddress, $errcode, $errstring, $timeout, $flags, $context)
 * @method static stream_socket_server($localaddress, $errcode, $errstring, $flags, $context)
 * @method static stream_socket_accept($serverstream, $timeout, $peername)
 * @method static stream_socket_get_name($stream, $want_peer)
 * @method static stream_socket_recvfrom($stream, $amount, $flags, $remote_addr)
 * @method static stream_socket_sendto($stream, $data, $flags, $target_addr)
 * @method static stream_socket_enable_crypto($stream, $enable, $cryptokind, $sessionstream)
 * @method static stream_socket_shutdown($stream, $how)
 * @method static stream_socket_pair($domain, $type, $protocol)
 * @method static stream_copy_to_stream($source, $dest, $maxlen, $pos)
 * @method static stream_get_contents($source, $maxlen, $offset)
 * @method static stream_supports_lock($stream)
 * @method static fgetcsv($fp, $length, $delimiter, $enclosure, $escape)
 * @method static fputcsv($fp, $fields, $delimiter, $enclosure, $escape_char)
 * @method static flock($fp, $operation, $wouldblock)
 * @method static get_meta_tags($filename, $use_include_path)
 * @method static stream_set_read_buffer($fp, $buffer)
 * @method static stream_set_write_buffer($fp, $buffer)
 * @method static set_file_buffer($fp, $buffer)
 * @method static stream_set_chunk_size($fp, $chunk_size)
 * @method static stream_set_blocking($socket, $mode)
 * @method static socket_set_blocking($socket, $mode)
 * @method static stream_get_meta_data($fp)
 * @method static stream_get_line($stream, $maxlen, $ending)
 * @method static stream_wrapper_register($protocol, $classname, $flags)
 * @method static stream_register_wrapper($protocol, $classname, $flags)
 * @method static stream_wrapper_unregister($protocol)
 * @method static stream_wrapper_restore($protocol)
 * @method static stream_get_wrappers()
 * @method static stream_get_transports()
 * @method static stream_resolve_include_path($filename)
 * @method static stream_is_local($stream)
 * @method static get_headers($url, $format, $context)
 * @method static stream_set_timeout($stream, $seconds, $microseconds)
 * @method static socket_set_timeout($stream, $seconds, $microseconds)
 * @method static socket_get_status($fp)
 * @method static realpath($path)
 * @method static fnmatch($pattern, $filename, $flags)
 * @method static fsockopen($hostname, $port, $errno, $errstr, $timeout)
 * @method static pfsockopen($hostname, $port, $errno, $errstr, $timeout)
 * @method static pack($format, $args)
 * @method static unpack($format, $input, $offset)
 * @method static get_browser($browser_name, $return_array)
 * @method static crypt($str, $salt)
 * @method static opendir($path, $context)
 * @method static closedir($dir_handle)
 * @method static chdir($directory)
 * @method static chroot($directory)
 * @method static getcwd()
 * @method static rewinddir($dir_handle)
 * @method static readdir($dir_handle)
 * @method static dir($directory, $context)
 * @method static scandir($dir, $sorting_order, $context)
 * @method static glob($pattern, $flags)
 * @method static fileatime($filename)
 * @method static filectime($filename)
 * @method static filegroup($filename)
 * @method static fileinode($filename)
 * @method static filemtime($filename)
 * @method static fileowner($filename)
 * @method static fileperms($filename)
 * @method static filesize($filename)
 * @method static filetype($filename)
 * @method static file_exists($filename)
 * @method static is_writable($filename)
 * @method static is_writeable($filename)
 * @method static is_readable($filename)
 * @method static is_executable($filename)
 * @method static is_file($filename)
 * @method static is_dir($filename)
 * @method static is_link($filename)
 * @method static stat($filename)
 * @method static lstat($filename)
 * @method static chown($filename, $user)
 * @method static chgrp($filename, $group)
 * @method static lchown($filename, $user)
 * @method static lchgrp($filename, $group)
 * @method static chmod($filename, $mode)
 * @method static touch($filename, $time, $atime)
 * @method static clearstatcache($clear_realpath_cache, $filename)
 * @method static disk_total_space($path)
 * @method static disk_free_space($path)
 * @method static diskfreespace($path)
 * @method static realpath_cache_size()
 * @method static realpath_cache_get()
 * @method static mail($to, $subject, $message, $additional_headers, $additional_parameters)
 * @method static ezmlm_hash($addr)
 * @method static openlog($ident, $option, $facility)
 * @method static syslog($priority, $message)
 * @method static closelog()
 * @method static lcg_value()
 * @method static metaphone($text, $phones)
 * @method static ob_start($user_function, $chunk_size, $flags)
 * @method static ob_flush()
 * @method static ob_clean()
 * @method static ob_end_flush()
 * @method static ob_end_clean()
 * @method static ob_get_flush()
 * @method static ob_get_clean()
 * @method static ob_get_length()
 * @method static ob_get_level()
 * @method static ob_get_status($full_status)
 * @method static ob_get_contents()
 * @method static ob_implicit_flush($flag)
 * @method static ob_list_handlers()
 * @method static ksort($arg, $sort_flags)
 * @method static krsort($arg, $sort_flags)
 * @method static natsort($arg)
 * @method static natcasesort($arg)
 * @method static asort($arg, $sort_flags)
 * @method static arsort($arg, $sort_flags)
 * @method static sort($arg, $sort_flags)
 * @method static rsort($arg, $sort_flags)
 * @method static usort($arg, $cmp_function)
 * @method static uasort($arg, $cmp_function)
 * @method static uksort($arg, $cmp_function)
 * @method static shuffle($arg)
 * @method static array_walk($input, $funcname, $userdata)
 * @method static array_walk_recursive($input, $funcname, $userdata)
 * @method static count($var, $mode)
 * @method static end($arg)
 * @method static prev($arg)
 * @method static next($arg)
 * @method static reset($arg)
 * @method static current($arg)
 * @method static key($arg)
 * @method static min($args)
 * @method static max($args)
 * @method static in_array($needle, $haystack, $strict)
 * @method static array_search($needle, $haystack, $strict)
 * @method static extract($arg, $extract_type, $prefix)
 * @method static compact($var_names)
 * @method static array_fill($start_key, $num, $val)
 * @method static array_fill_keys($keys, $val)
 * @method static range($low, $high, $step)
 * @method static array_multisort($arr1, $sort_order, $sort_flags, $arr2)
 * @method static array_push($stack, $vars)
 * @method static array_pop($stack)
 * @method static array_shift($stack)
 * @method static array_unshift($stack, $vars)
 * @method static array_splice($arg, $offset, $length, $replacement)
 * @method static array_slice($arg, $offset, $length, $preserve_keys)
 * @method static array_merge($arr1, $arrays)
 * @method static array_merge_recursive($arr1, $arrays)
 * @method static array_replace($arr1, $arrays)
 * @method static array_replace_recursive($arr1, $arrays)
 * @method static array_keys($arg, $search_value, $strict)
 * @method static array_values($arg)
 * @method static array_count_values($arg)
 * @method static array_column($arg, $column_key, $index_key)
 * @method static array_reverse($input, $preserve_keys)
 * @method static array_reduce($arg, $callback, $initial)
 * @method static array_pad($arg, $pad_size, $pad_value)
 * @method static array_flip($arg)
 * @method static array_change_key_case($input, $case)
 * @method static array_rand($arg, $num_req)
 * @method static array_unique($arg, $flags)
 * @method static array_intersect($arr1, $arrays)
 * @method static array_intersect_key($arr1, $arrays)
 * @method static array_intersect_ukey($arr1, $arr2, $callback_key_compare_func)
 * @method static array_uintersect($arr1, $arr2, $callback_data_compare_func)
 * @method static array_intersect_assoc($arr1, $arrays)
 * @method static array_uintersect_assoc($arr1, $arr2, $callback_data_compare_func)
 * @method static array_intersect_uassoc($arr1, $arr2, $callback_key_compare_func)
 * @method static array_uintersect_uassoc($arr1, $arr2, $callback_data_compare_func, $callback_key_compare_func)
 * @method static array_diff($arr1, $arrays)
 * @method static array_diff_key($arr1, $arrays)
 * @method static array_diff_ukey($arr1, $arr2, $callback_key_comp_func)
 * @method static array_udiff($arr1, $arr2, $callback_data_comp_func)
 * @method static array_diff_assoc($arr1, $arrays)
 * @method static array_udiff_assoc($arr1, $arr2, $callback_key_comp_func)
 * @method static array_diff_uassoc($arr1, $arr2, $callback_data_comp_func)
 * @method static array_udiff_uassoc($arr1, $arr2, $callback_data_comp_func, $callback_key_comp_func)
 * @method static array_sum($arg)
 * @method static array_product($arg)
 * @method static array_filter($arg, $callback, $use_keys)
 * @method static array_map($callback, $arrays)
 * @method static array_chunk($arg, $size, $preserve_keys)
 * @method static array_combine($keys, $values)
 * @method static array_key_exists($key, $search)
 * @method static pos($arg)
 * @method static sizeof($var, $mode)
 * @method static key_exists($key, $search)
 * @method static assert($assertion, $description)
 * @method static assert_options($what, $value)
 * @method static version_compare($ver1, $ver2, $oper)
 * @method static ftok($pathname, $proj)
 * @method static str_rot13($str)
 * @method static stream_get_filters()
 * @method static stream_filter_register($filtername, $classname)
 * @method static stream_bucket_make_writeable($brigade)
 * @method static stream_bucket_prepend($brigade, $bucket)
 * @method static stream_bucket_append($brigade, $bucket)
 * @method static stream_bucket_new($stream, $buffer)
 * @method static output_add_rewrite_var($name, $value)
 * @method static output_reset_rewrite_vars()
 * @method static sys_get_temp_dir()
 * @method static xhprof_enable($flags, $options)
 * @method static xhprof_disable()
 * @method static xhprof_sample_enable()
 * @method static xhprof_sample_disable()
 * @method static pdo_drivers()
 * @method static xml_parser_create($encoding)
 * @method static xml_parser_create_ns($encoding, $sep)
 * @method static xml_set_object($parser, $obj)
 * @method static xml_set_element_handler($parser, $shdl, $ehdl)
 * @method static xml_set_character_data_handler($parser, $hdl)
 * @method static xml_set_processing_instruction_handler($parser, $hdl)
 * @method static xml_set_default_handler($parser, $hdl)
 * @method static xml_set_unparsed_entity_decl_handler($parser, $hdl)
 * @method static xml_set_notation_decl_handler($parser, $hdl)
 * @method static xml_set_external_entity_ref_handler($parser, $hdl)
 * @method static xml_set_start_namespace_decl_handler($parser, $hdl)
 * @method static xml_set_end_namespace_decl_handler($parser, $hdl)
 * @method static xml_parse($parser, $data, $isfinal)
 * @method static xml_parse_into_struct($parser, $data, $values, $index)
 * @method static xml_get_error_code($parser)
 * @method static xml_error_string($code)
 * @method static xml_get_current_line_number($parser)
 * @method static xml_get_current_column_number($parser)
 * @method static xml_get_current_byte_index($parser)
 * @method static xml_parser_free($parser)
 * @method static xml_parser_set_option($parser, $option, $value)
 * @method static xml_parser_get_option($parser, $option)
 * @method static utf8_encode($data)
 * @method static utf8_decode($data)
 * @method static apcu_cache_info($limited)
 * @method static apcu_clear_cache()
 * @method static apcu_sma_info($limited)
 * @method static apcu_key_info($key)
 * @method static apcu_enabled()
 * @method static apcu_store($key, $var, $ttl)
 * @method static apcu_fetch($key, $success)
 * @method static apcu_delete($keys)
 * @method static apcu_add($key, $var, $ttl)
 * @method static apcu_inc($key, $step, $success)
 * @method static apcu_dec($key, $step, $success)
 * @method static apcu_cas($key, $old, $new)
 * @method static apcu_exists($keys)
 * @method static apcu_entry($key, $generator, $ttl)
 * @method static apc_cache_info($type, $limited)
 * @method static apc_clear_cache($type)
 * @method static apc_store($key, $var, $ttl)
 * @method static apc_fetch($key, $success)
 * @method static apc_enabled()
 * @method static apc_delete($keys)
 * @method static apc_add($key, $var, $ttl)
 * @method static apc_sma_info($limited)
 * @method static apc_inc($key, $step, $success)
 * @method static apc_dec($key, $step, $success)
 * @method static apc_cas($key, $old, $new)
 * @method static apc_exists($keys)
 * @method static jdtogregorian($juliandaycount)
 * @method static gregoriantojd($month, $day, $year)
 * @method static jdtojulian($juliandaycount)
 * @method static juliantojd($month, $day, $year)
 * @method static jdtojewish($juliandaycount, $hebrew, $fl)
 * @method static jewishtojd($month, $day, $year)
 * @method static jdtofrench($juliandaycount)
 * @method static frenchtojd($month, $day, $year)
 * @method static jddayofweek($juliandaycount, $mode)
 * @method static jdmonthname($juliandaycount, $mode)
 * @method static easter_date($year)
 * @method static easter_days($year, $method)
 * @method static unixtojd($timestamp)
 * @method static jdtounix($jday)
 * @method static cal_to_jd($calendar, $month, $day, $year)
 * @method static cal_from_jd($jd, $calendar)
 * @method static cal_days_in_month($calendar, $month, $year)
 * @method static cal_info($calendar)
 * @method static ctype_alnum($text)
 * @method static ctype_alpha($text)
 * @method static ctype_cntrl($text)
 * @method static ctype_digit($text)
 * @method static ctype_lower($text)
 * @method static ctype_graph($text)
 * @method static ctype_print($text)
 * @method static ctype_punct($text)
 * @method static ctype_space($text)
 * @method static ctype_upper($text)
 * @method static ctype_xdigit($text)
 * @method static curl_init($url)
 * @method static curl_copy_handle($ch)
 * @method static curl_version($version)
 * @method static curl_setopt($ch, $option, $value)
 * @method static curl_setopt_array($ch, $options)
 * @method static curl_exec($ch)
 * @method static curl_getinfo($ch, $option)
 * @method static curl_error($ch)
 * @method static curl_errno($ch)
 * @method static curl_close($ch)
 * @method static curl_strerror($errornum)
 * @method static curl_multi_strerror($errornum)
 * @method static curl_share_strerror($errornum)
 * @method static curl_reset($ch)
 * @method static curl_escape($ch, $str)
 * @method static curl_unescape($ch, $str)
 * @method static curl_pause($ch, $bitmask)
 * @method static curl_multi_init()
 * @method static curl_multi_add_handle($mh, $ch)
 * @method static curl_multi_remove_handle($mh, $ch)
 * @method static curl_multi_select($mh, $timeout)
 * @method static curl_multi_exec($mh, $still_running)
 * @method static curl_multi_getcontent($ch)
 * @method static curl_multi_info_read($mh, $msgs_in_queue)
 * @method static curl_multi_close($mh)
 * @method static curl_multi_errno($mh)
 * @method static curl_multi_setopt($sh, $option, $value)
 * @method static curl_share_init()
 * @method static curl_share_close($sh)
 * @method static curl_share_setopt($sh, $option, $value)
 * @method static curl_share_errno($sh)
 * @method static curl_file_create($filename, $mimetype, $postname)
 * @method static dom_import_simplexml($node)
 * @method static exif_read_data($filename, $sections_needed, $sub_arrays, $read_thumbnail)
 * @method static read_exif_data($filename, $sections_needed, $sub_arrays, $read_thumbnail)
 * @method static exif_tagname($index)
 * @method static exif_thumbnail($filename, $width, $height, $imagetype)
 * @method static exif_imagetype($imagefile)
 * @method static finfo_open($options, $arg)
 * @method static finfo_close($finfo)
 * @method static finfo_set_flags($finfo, $options)
 * @method static finfo_file($finfo, $filename, $options, $context)
 * @method static finfo_buffer($finfo, $string, $options, $context)
 * @method static mime_content_type($string)
 * @method static ftp_connect($host, $port, $timeout)
 * @method static ftp_ssl_connect($host, $port, $timeout)
 * @method static ftp_login($ftp, $username, $password)
 * @method static ftp_pwd($ftp)
 * @method static ftp_cdup($ftp)
 * @method static ftp_chdir($ftp, $directory)
 * @method static ftp_exec($ftp, $command)
 * @method static ftp_raw($ftp, $command)
 * @method static ftp_mkdir($ftp, $directory)
 * @method static ftp_rmdir($ftp, $directory)
 * @method static ftp_chmod($ftp, $mode, $filename)
 * @method static ftp_alloc($ftp, $size, $response)
 * @method static ftp_nlist($ftp, $directory)
 * @method static ftp_rawlist($ftp, $directory, $recursive)
 * @method static ftp_systype($ftp)
 * @method static ftp_pasv($ftp, $pasv)
 * @method static ftp_get($ftp, $local_file, $remote_file, $mode, $resume_pos)
 * @method static ftp_fget($ftp, $fp, $remote_file, $mode, $resumepos)
 * @method static ftp_put($ftp, $remote_file, $local_file, $mode, $startpos)
 * @method static ftp_fput($ftp, $remote_file, $fp, $mode, $startpos)
 * @method static ftp_size($ftp, $filename)
 * @method static ftp_mdtm($ftp, $filename)
 * @method static ftp_rename($ftp, $src, $dest)
 * @method static ftp_delete($ftp, $file)
 * @method static ftp_site($ftp, $cmd)
 * @method static ftp_close($ftp)
 * @method static ftp_set_option($ftp, $option, $value)
 * @method static ftp_get_option($ftp, $option)
 * @method static ftp_nb_fget($ftp, $fp, $remote_file, $mode, $resumepos)
 * @method static ftp_nb_get($ftp, $local_file, $remote_file, $mode, $resume_pos)
 * @method static ftp_nb_continue($ftp)
 * @method static ftp_nb_put($ftp, $remote_file, $local_file, $mode, $startpos)
 * @method static ftp_nb_fput($ftp, $remote_file, $fp, $mode, $startpos)
 * @method static ftp_quit($ftp)
 * @method static textdomain($domain)
 * @method static gettext($msgid)
 * @method static _($msgid)
 * @method static dgettext($domain_name, $msgid)
 * @method static dcgettext($domain_name, $msgid, $category)
 * @method static bindtextdomain($domain_name, $dir)
 * @method static ngettext($msgid1, $msgid2, $count)
 * @method static dngettext($domain, $msgid1, $msgid2, $count)
 * @method static dcngettext($domain, $msgid1, $msgid2, $count, $category)
 * @method static bind_textdomain_codeset($domain, $codeset)
 * @method static iconv($in_charset, $out_charset, $str)
 * @method static iconv_get_encoding($type)
 * @method static iconv_set_encoding($type, $charset)
 * @method static iconv_strlen($str, $charset)
 * @method static iconv_substr($str, $offset, $length, $charset)
 * @method static iconv_strpos($haystack, $needle, $offset, $charset)
 * @method static iconv_strrpos($haystack, $needle, $charset)
 * @method static iconv_mime_encode($field_name, $field_value, $preference)
 * @method static iconv_mime_decode($encoded_string, $mode, $charset)
 * @method static iconv_mime_decode_headers($headers, $mode, $charset)
 * @method static igbinary_serialize($value)
 * @method static igbinary_unserialize($str)
 * @method static json_encode($value, $options, $depth)
 * @method static json_decode($json, $assoc, $depth, $options)
 * @method static json_last_error()
 * @method static json_last_error_msg()
 * @method static mb_convert_case($sourcestring, $mode, $encoding)
 * @method static mb_strtoupper($sourcestring, $encoding)
 * @method static mb_strtolower($sourcestring, $encoding)
 * @method static mb_language($language)
 * @method static mb_internal_encoding($encoding)
 * @method static mb_http_input($type)
 * @method static mb_http_output($encoding)
 * @method static mb_detect_order($encoding)
 * @method static mb_substitute_character($substchar)
 * @method static mb_parse_str($encoded_string, $result)
 * @method static mb_output_handler($contents, $status)
 * @method static mb_preferred_mime_name($encoding)
 * @method static mb_strlen($str, $encoding)
 * @method static mb_strpos($haystack, $needle, $offset, $encoding)
 * @method static mb_strrpos($haystack, $needle, $offset, $encoding)
 * @method static mb_stripos($haystack, $needle, $offset, $encoding)
 * @method static mb_strripos($haystack, $needle, $offset, $encoding)
 * @method static mb_strstr($haystack, $needle, $part, $encoding)
 * @method static mb_strrchr($haystack, $needle, $part, $encoding)
 * @method static mb_stristr($haystack, $needle, $part, $encoding)
 * @method static mb_strrichr($haystack, $needle, $part, $encoding)
 * @method static mb_substr_count($haystack, $needle, $encoding)
 * @method static mb_substr($str, $start, $length, $encoding)
 * @method static mb_strcut($str, $start, $length, $encoding)
 * @method static mb_strwidth($str, $encoding)
 * @method static mb_strimwidth($str, $start, $width, $trimmarker, $encoding)
 * @method static mb_convert_encoding($str, $to, $from)
 * @method static mb_detect_encoding($str, $encoding_list, $strict)
 * @method static mb_list_encodings()
 * @method static mb_encoding_aliases($encoding)
 * @method static mb_convert_kana($str, $option, $encoding)
 * @method static mb_encode_mimeheader($str, $charset, $transfer, $linefeed, $indent)
 * @method static mb_decode_mimeheader($string)
 * @method static mb_convert_variables($to, $from, $vars)
 * @method static mb_encode_numericentity($string, $convmap, $encoding, $is_hex)
 * @method static mb_decode_numericentity($string, $convmap, $encoding)
 * @method static mb_send_mail($to, $subject, $message, $additional_headers, $additional_parameters)
 * @method static mb_get_info($type)
 * @method static mb_check_encoding($var, $encoding)
 * @method static mb_regex_encoding($encoding)
 * @method static mb_regex_set_options($options)
 * @method static mb_ereg($pattern, $string, $registers)
 * @method static mb_eregi($pattern, $string, $registers)
 * @method static mb_ereg_replace($pattern, $replacement, $string, $option)
 * @method static mb_eregi_replace($pattern, $replacement, $string)
 * @method static mb_ereg_replace_callback($pattern, $callback, $string, $option)
 * @method static mb_split($pattern, $string, $limit)
 * @method static mb_ereg_match($pattern, $string, $option)
 * @method static mb_ereg_search($pattern, $option)
 * @method static mb_ereg_search_pos($pattern, $option)
 * @method static mb_ereg_search_regs($pattern, $option)
 * @method static mb_ereg_search_init($string, $pattern, $option)
 * @method static mb_ereg_search_getregs()
 * @method static mb_ereg_search_getpos()
 * @method static mb_ereg_search_setpos($position)
 * @method static mbregex_encoding($encoding)
 * @method static mbereg($pattern, $string, $registers)
 * @method static mberegi($pattern, $string, $registers)
 * @method static mbereg_replace($pattern, $replacement, $string, $option)
 * @method static mberegi_replace($pattern, $replacement, $string)
 * @method static mbsplit($pattern, $string, $limit)
 * @method static mbereg_match($pattern, $string, $option)
 * @method static mbereg_search($pattern, $option)
 * @method static mbereg_search_pos($pattern, $option)
 * @method static mbereg_search_regs($pattern, $option)
 * @method static mbereg_search_init($string, $pattern, $option)
 * @method static mbereg_search_getregs()
 * @method static mbereg_search_getpos()
 * @method static mbereg_search_setpos($position)
 * @method static pg_connect($connection_string, $connect_type, $host, $port, $options, $tty, $database)
 * @method static pg_pconnect($connection_string, $host, $port, $options, $tty, $database)
 * @method static pg_connect_poll($connection)
 * @method static pg_close($connection)
 * @method static pg_connection_status($connection)
 * @method static pg_connection_busy($connection)
 * @method static pg_connection_reset($connection)
 * @method static pg_host($connection)
 * @method static pg_dbname($connection)
 * @method static pg_port($connection)
 * @method static pg_tty($connection)
 * @method static pg_options($connection)
 * @method static pg_version($connection)
 * @method static pg_ping($connection)
 * @method static pg_parameter_status($connection, $param_name)
 * @method static pg_transaction_status($connection)
 * @method static pg_query($connection, $query)
 * @method static pg_query_params($connection, $query, $params)
 * @method static pg_prepare($connection, $stmtname, $query)
 * @method static pg_execute($connection, $stmtname, $params)
 * @method static pg_send_query($connection, $query)
 * @method static pg_send_query_params($connection, $query, $params)
 * @method static pg_send_prepare($connection, $stmtname, $query)
 * @method static pg_send_execute($connection, $stmtname, $params)
 * @method static pg_cancel_query($connection)
 * @method static pg_fetch_result($result, $row_number, $field_name)
 * @method static pg_fetch_row($result, $row, $result_type)
 * @method static pg_fetch_assoc($result, $row)
 * @method static pg_fetch_array($result, $row, $result_type)
 * @method static pg_fetch_object($result, $row, $class_name, $l, $ctor_params)
 * @method static pg_fetch_all($result, $result_type)
 * @method static pg_fetch_all_columns($result, $column_number)
 * @method static pg_affected_rows($result)
 * @method static pg_get_result($connection)
 * @method static pg_result_seek($result, $offset)
 * @method static pg_result_status($result, $result_type)
 * @method static pg_free_result($result)
 * @method static pg_last_oid($result)
 * @method static pg_num_rows($result)
 * @method static pg_num_fields($result)
 * @method static pg_field_name($result, $field_number)
 * @method static pg_field_num($result, $field_name)
 * @method static pg_field_size($result, $field_number)
 * @method static pg_field_type($result, $field_number)
 * @method static pg_field_type_oid($result, $field_number)
 * @method static pg_field_prtlen($result, $row, $field_name_or_number)
 * @method static pg_field_is_null($result, $row, $field_name_or_number)
 * @method static pg_field_table($result, $field_number, $oid_only)
 * @method static pg_get_notify($connection, $e)
 * @method static pg_socket($connection)
 * @method static pg_consume_input($connection)
 * @method static pg_flush($connection)
 * @method static pg_get_pid($connection)
 * @method static pg_result_error($result)
 * @method static pg_result_error_field($result, $fieldcode)
 * @method static pg_last_error($connection)
 * @method static pg_last_notice($connection, $option)
 * @method static pg_put_line($connection, $query)
 * @method static pg_end_copy($connection)
 * @method static pg_copy_to($connection, $table_name, $delimiter, $null_as)
 * @method static pg_copy_from($connection, $table_name, $rows, $delimiter, $null_as)
 * @method static pg_trace($filename, $mode, $connection)
 * @method static pg_untrace($connection)
 * @method static pg_lo_create($connection, $large_object_id)
 * @method static pg_lo_unlink($connection, $large_object_oid)
 * @method static pg_lo_open($connection, $large_object_oid, $mode)
 * @method static pg_lo_close($large_object)
 * @method static pg_lo_read($large_object, $len)
 * @method static pg_lo_write($large_object, $buf, $len)
 * @method static pg_lo_read_all($large_object)
 * @method static pg_lo_import($connection, $filename, $large_object_oid)
 * @method static pg_lo_export($connection, $objoid, $filename)
 * @method static pg_lo_seek($large_object, $offset, $whence)
 * @method static pg_lo_tell($large_object)
 * @method static pg_lo_truncate($large_object, $size)
 * @method static pg_escape_string($connection, $data)
 * @method static pg_escape_bytea($connection, $data)
 * @method static pg_unescape_bytea($data)
 * @method static pg_escape_literal($connection, $data)
 * @method static pg_escape_identifier($connection, $data)
 * @method static pg_set_error_verbosity($connection, $verbosity)
 * @method static pg_client_encoding($connection)
 * @method static pg_set_client_encoding($connection, $encoding)
 * @method static pg_meta_data($db, $table)
 * @method static pg_convert($db, $table, $values, $options)
 * @method static pg_insert($db, $table, $values, $options)
 * @method static pg_update($db, $table, $fields, $ids, $options)
 * @method static pg_delete($db, $table, $ids, $options)
 * @method static pg_select($db, $table, $ids, $options, $result_type)
 * @method static pg_exec($connection, $query)
 * @method static pg_getlastoid($result)
 * @method static pg_cmdtuples($result)
 * @method static pg_errormessage($connection)
 * @method static pg_numrows($result)
 * @method static pg_numfields($result)
 * @method static pg_fieldname($result, $field_number)
 * @method static pg_fieldsize($result, $field_number)
 * @method static pg_fieldtype($result, $field_number)
 * @method static pg_fieldnum($result, $field_name)
 * @method static pg_fieldprtlen($result, $row, $field_name_or_number)
 * @method static pg_fieldisnull($result, $row, $field_name_or_number)
 * @method static pg_freeresult($result)
 * @method static pg_result($connection)
 * @method static pg_loreadall($large_object)
 * @method static pg_locreate($connection, $large_object_id)
 * @method static pg_lounlink($connection, $large_object_oid)
 * @method static pg_loopen($connection, $large_object_oid, $mode)
 * @method static pg_loclose($large_object)
 * @method static pg_loread($large_object, $len)
 * @method static pg_lowrite($large_object, $buf, $len)
 * @method static pg_loimport($connection, $filename, $large_object_oid)
 * @method static pg_loexport($connection, $objoid, $filename)
 * @method static pg_clientencoding($connection)
 * @method static pg_setclientencoding($connection, $encoding)
 * @method static posix_kill($pid, $sig)
 * @method static posix_getpid()
 * @method static posix_getppid()
 * @method static posix_getuid()
 * @method static posix_setuid($uid)
 * @method static posix_geteuid()
 * @method static posix_seteuid($uid)
 * @method static posix_getgid()
 * @method static posix_setgid($gid)
 * @method static posix_getegid()
 * @method static posix_setegid($gid)
 * @method static posix_getgroups()
 * @method static posix_getlogin()
 * @method static posix_getpgrp()
 * @method static posix_setsid()
 * @method static posix_setpgid($pid, $pgid)
 * @method static posix_getpgid($pid)
 * @method static posix_getsid($pid)
 * @method static posix_uname()
 * @method static posix_times()
 * @method static posix_ctermid()
 * @method static posix_ttyname($fd)
 * @method static posix_isatty($fd)
 * @method static posix_getcwd()
 * @method static posix_mkfifo($pathname, $mode)
 * @method static posix_mknod($pathname, $mode, $major, $minor)
 * @method static posix_access($file, $mode)
 * @method static posix_getgrnam($name)
 * @method static posix_getgrgid($gid)
 * @method static posix_getpwnam($username)
 * @method static posix_getpwuid($uid)
 * @method static posix_getrlimit()
 * @method static posix_setrlimit($resource, $softlimit, $hardlimit)
 * @method static posix_get_last_error()
 * @method static posix_errno()
 * @method static posix_strerror($errno)
 * @method static posix_initgroups($name, $base_group_id)
 * @method static readline($prompt)
 * @method static readline_info($varname, $newvalue)
 * @method static readline_add_history($prompt)
 * @method static readline_clear_history()
 * @method static readline_read_history($filename)
 * @method static readline_write_history($filename)
 * @method static readline_completion_function($funcname)
 * @method static readline_callback_handler_install($prompt, $callback)
 * @method static readline_callback_read_char()
 * @method static readline_callback_handler_remove()
 * @method static readline_redisplay()
 * @method static readline_on_new_line()
 * @method static runkit_zval_inspect($value)
 * @method static runkit_object_id($obj)
 * @method static runkit_superglobals()
 * @method static runkit_function_add($funcname, $arglist_or_closure, $code_or_doc_comment, $return_by_reference, $doc_comment, $return_type)
 * @method static runkit_function_remove($funcname)
 * @method static runkit_function_rename($funcname, $newname)
 * @method static runkit_function_redefine($funcname, $arglist_or_closure, $code_or_doc_comment, $return_by_reference, $doc_comment, $return_type)
 * @method static runkit_function_copy($funcname, $targetname)
 * @method static runkit_method_add($classname, $methodname, $arglist_or_closure, $code_or_flags, $flags_or_doc_comment, $doc_comment, $return_type)
 * @method static runkit_method_redefine($classname, $methodname, $arglist_or_closure, $code_or_flags, $flags_or_doc_comment, $doc_comment, $return_type)
 * @method static runkit_method_remove($classname, $methodname)
 * @method static runkit_method_rename($classname, $methodname, $newname)
 * @method static runkit_method_copy($dClass, $dMethod, $sClass, $sMethod)
 * @method static runkit_constant_redefine($constname, $value, $newVisibility)
 * @method static runkit_constant_remove($constname)
 * @method static runkit_constant_add($constname, $value, $newVisibility)
 * @method static shmop_open($key, $flags, $mode, $size)
 * @method static shmop_read($shmid, $start, $count)
 * @method static shmop_close($shmid)
 * @method static shmop_size($shmid)
 * @method static shmop_write($shmid, $data, $offset)
 * @method static shmop_delete($shmid)
 * @method static simplexml_load_file($filename, $class_name, $options, $ns, $is_prefix)
 * @method static simplexml_load_string($data, $class_name, $options, $ns, $is_prefix)
 * @method static simplexml_import_dom($node, $class_name)
 * @method static socket_select($read_fds, $write_fds, $except_fds, $tv_sec, $tv_usec)
 * @method static socket_create($domain, $type, $protocol)
 * @method static socket_create_listen($port, $backlog)
 * @method static socket_create_pair($domain, $type, $protocol, $fd)
 * @method static socket_accept($socket)
 * @method static socket_set_nonblock($socket)
 * @method static socket_set_block($socket)
 * @method static socket_listen($socket, $backlog)
 * @method static socket_close($socket)
 * @method static socket_write($socket, $buf, $length)
 * @method static socket_read($socket, $length, $type)
 * @method static socket_getsockname($socket, $addr, $port)
 * @method static socket_getpeername($socket, $addr, $port)
 * @method static socket_connect($socket, $addr, $port)
 * @method static socket_strerror($errno)
 * @method static socket_bind($socket, $addr, $port)
 * @method static socket_recv($socket, $buf, $len, $flags)
 * @method static socket_send($socket, $buf, $len, $flags)
 * @method static socket_recvfrom($socket, $buf, $len, $flags, $name, $port)
 * @method static socket_sendto($socket, $buf, $len, $flags, $addr, $port)
 * @method static socket_get_option($socket, $level, $optname)
 * @method static socket_set_option($socket, $level, $optname, $optval)
 * @method static socket_shutdown($socket, $how)
 * @method static socket_last_error($socket)
 * @method static socket_clear_error($socket)
 * @method static socket_import_stream($stream)
 * @method static socket_export_stream($socket)
 * @method static socket_sendmsg($socket, $msghdr, $flags)
 * @method static socket_recvmsg($socket, $msghdr, $flags)
 * @method static socket_cmsg_space($level, $type)
 * @method static socket_getopt($socket, $level, $optname)
 * @method static socket_setopt($socket, $level, $optname, $optval)
 * @method static msg_get_queue($key, $perms)
 * @method static msg_send($queue, $msgtype, $message, $serialize, $blocking, $errorcode)
 * @method static msg_receive($queue, $desiredmsgtype, $msgtype, $maxsize, $message, $unserialize, $flags, $errorcode)
 * @method static msg_remove_queue($queue)
 * @method static msg_stat_queue($queue)
 * @method static msg_set_queue($queue, $data)
 * @method static msg_queue_exists($key)
 * @method static sem_get($key, $max_acquire, $perm, $auto_release)
 * @method static sem_acquire($sem_identifier, $nowait)
 * @method static sem_release($sem_identifier)
 * @method static sem_remove($sem_identifier)
 * @method static shm_attach($key, $memsize, $perm)
 * @method static shm_remove($shm_identifier)
 * @method static shm_detach($shm_identifier)
 * @method static shm_put_var($shm_identifier, $variable_key, $variable)
 * @method static shm_has_var($id, $variable_key)
 * @method static shm_get_var($id, $variable_key)
 * @method static shm_remove_var($id, $variable_key)
 * @method static token_get_all($source, $flags)
 * @method static token_name($token)
 * @method static uuid_create($uuid_type)
 * @method static uuid_is_valid($uuid)
 * @method static uuid_compare($uuid1, $uuid2)
 * @method static uuid_is_null($uuid)
 * @method static uuid_type($uuid)
 * @method static uuid_variant($uuid)
 * @method static uuid_time($uuid)
 * @method static uuid_mac($uuid)
 * @method static uuid_parse($uuid)
 * @method static uuid_unparse($uuid)
 * @method static wddx_serialize_value($var, $comment)
 * @method static wddx_serialize_vars($var_names)
 * @method static wddx_packet_start($comment)
 * @method static wddx_packet_end($packet_id)
 * @method static wddx_add_vars($packet_id, $var_names)
 * @method static wddx_deserialize($packet)
 * @method static xmlwriter_open_uri($uri)
 * @method static xmlwriter_open_memory()
 * @method static xmlwriter_set_indent($xmlwriter, $indent)
 * @method static xmlwriter_set_indent_string($xmlwriter, $indentString)
 * @method static xmlwriter_start_comment($xmlwriter)
 * @method static xmlwriter_end_comment($xmlwriter)
 * @method static xmlwriter_start_attribute($xmlwriter, $name)
 * @method static xmlwriter_end_attribute($xmlwriter)
 * @method static xmlwriter_write_attribute($xmlwriter, $name, $value)
 * @method static xmlwriter_start_attribute_ns($xmlwriter, $prefix, $name, $uri)
 * @method static xmlwriter_write_attribute_ns($xmlwriter, $prefix, $name, $uri, $content)
 * @method static xmlwriter_start_element($xmlwriter, $name)
 * @method static xmlwriter_end_element($xmlwriter)
 * @method static xmlwriter_full_end_element($xmlwriter)
 * @method static xmlwriter_start_element_ns($xmlwriter, $prefix, $name, $uri)
 * @method static xmlwriter_write_element($xmlwriter, $name, $content)
 * @method static xmlwriter_write_element_ns($xmlwriter, $prefix, $name, $uri, $content)
 * @method static xmlwriter_start_pi($xmlwriter, $target)
 * @method static xmlwriter_end_pi($xmlwriter)
 * @method static xmlwriter_write_pi($xmlwriter, $target, $content)
 * @method static xmlwriter_start_cdata($xmlwriter)
 * @method static xmlwriter_end_cdata($xmlwriter)
 * @method static xmlwriter_write_cdata($xmlwriter, $content)
 * @method static xmlwriter_text($xmlwriter, $content)
 * @method static xmlwriter_write_raw($xmlwriter, $content)
 * @method static xmlwriter_start_document($xmlwriter, $version, $encoding, $standalone)
 * @method static xmlwriter_end_document($xmlwriter)
 * @method static xmlwriter_write_comment($xmlwriter, $content)
 * @method static xmlwriter_start_dtd($xmlwriter, $qualifiedName, $publicId, $systemId)
 * @method static xmlwriter_end_dtd($xmlwriter)
 * @method static xmlwriter_write_dtd($xmlwriter, $name, $publicId, $systemId, $subset)
 * @method static xmlwriter_start_dtd_element($xmlwriter, $qualifiedName)
 * @method static xmlwriter_end_dtd_element($xmlwriter)
 * @method static xmlwriter_write_dtd_element($xmlwriter, $name, $content)
 * @method static xmlwriter_start_dtd_attlist($xmlwriter, $name)
 * @method static xmlwriter_end_dtd_attlist($xmlwriter)
 * @method static xmlwriter_write_dtd_attlist($xmlwriter, $name, $content)
 * @method static xmlwriter_start_dtd_entity($xmlwriter, $name, $isparam)
 * @method static xmlwriter_end_dtd_entity($xmlwriter)
 * @method static xmlwriter_write_dtd_entity($xmlwriter, $name, $content)
 * @method static xmlwriter_output_memory($xmlwriter, $flush)
 * @method static xmlwriter_flush($xmlwriter, $empty)
 * @method static opcache_reset()
 * @method static opcache_invalidate($script, $force)
 * @method static opcache_compile_file($file)
 * @method static opcache_is_script_cached($script)
 * @method static opcache_get_configuration()
 * @method static opcache_get_status($fetch_scripts)
 * @method static xdebug_get_stack_depth()
 * @method static xdebug_get_function_stack()
 * @method static xdebug_get_formatted_function_stack()
 * @method static xdebug_print_function_stack($message, $options)
 * @method static xdebug_get_declared_vars()
 * @method static xdebug_call_class($depth)
 * @method static xdebug_call_function($depth)
 * @method static xdebug_call_file($depth)
 * @method static xdebug_call_line($depth)
 * @method static xdebug_var_dump($var)
 * @method static xdebug_debug_zval($var)
 * @method static xdebug_debug_zval_stdout($var)
 * @method static xdebug_enable()
 * @method static xdebug_disable()
 * @method static xdebug_is_enabled()
 * @method static xdebug_break()
 * @method static xdebug_start_trace($fname, $options)
 * @method static xdebug_stop_trace()
 * @method static xdebug_get_tracefile_name()
 * @method static xdebug_get_profiler_filename()
 * @method static xdebug_dump_aggr_profiling_data($prefix)
 * @method static xdebug_clear_aggr_profiling_data()
 * @method static xdebug_memory_usage()
 * @method static xdebug_peak_memory_usage()
 * @method static xdebug_time_index()
 * @method static xdebug_start_error_collection()
 * @method static xdebug_stop_error_collection()
 * @method static xdebug_get_collected_errors($clear)
 * @method static xdebug_start_function_monitor($functions_to_monitor)
 * @method static xdebug_stop_function_monitor()
 * @method static xdebug_get_monitored_functions($clear)
 * @method static xdebug_start_code_coverage($options)
 * @method static xdebug_stop_code_coverage($cleanup)
 * @method static xdebug_get_code_coverage()
 * @method static xdebug_code_coverage_started()
 * @method static xdebug_get_function_count()
 * @method static xdebug_dump_superglobals()
 * @method static xdebug_get_headers()
 * @method static dl($extension_filename)
 * @method static cli_set_process_title($title)
 * @method static cli_get_process_title()
 */
class ResultOf
{
    use InternalFunctionTrait;

    public static function __callStatic(string $name, array $arguments)
    {
        if ($func = static::handleInternalFunctionCall($name, $arguments)) {
            return $func;
        }

        throw new \Exception('Unknown procedure: ' . $name);
    }
}
