<?php
/**
 * Copyright (c) 2017 JD Williams
 *
 * This file is part of PHP-Genny, a library built by JD Williams. PHP-Genny is free software; you can
 * redistribute it and/or modify it under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your option) any later version.
 *
 * PHP-Genny is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details. You should have received a copy of the GNU Lesser General Public
 * License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * You should have received a copy of the GNU General Public License along with Unify. If not, see
 * <http://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace JDWil\PhpGenny\Builder\Node\Traits;

use JDWil\PhpGenny\Builder\Node\HasNodeBehaviorInterface;

/**
 * Trait NodeBehaviorTrait
 */
trait NodeBehaviorTrait
{
    /**
     * @var int
     */
    public $phpTargetVersion = 70;

    /**
     * @var bool
     */
    public $autoGenerateDocBlocks = false;

    /**
     * @var bool
     */
    protected $useStrict = false;

    /**
     * @var bool
     */
    protected $preferDefaultsSetInConstructor = false;

    /**
     * @param HasNodeBehaviorInterface $b
     */
    public function copyBehaviorFrom(HasNodeBehaviorInterface $b)
    {
        $this->autoGenerateDocBlocks = $b->getAutoGenerateDocBlocks();
        $this->phpTargetVersion = $b->getPhpTargetVersion();
        $this->useStrict = $b->getUseStrictTypes();
        $this->preferDefaultsSetInConstructor = $b->getPreferDefaultsSetInConstructor();
    }

    /**
     * @return $this
     */
    public function autoGenerateDocBlocks()
    {
        $this->autoGenerateDocBlocks = true;

        return $this;
    }

    /**
     * @param int $version
     */
    public function setPhpTargetVersion(int $version)
    {
        $this->phpTargetVersion = $version;
    }

    /**
     * @return int
     */
    public function getPhpTargetVersion(): int
    {
        return $this->phpTargetVersion;
    }

    /**
     * @return bool
     */
    public function getAutoGenerateDocBlocks(): bool
    {
        return $this->autoGenerateDocBlocks;
    }

    /**
     * @return $this
     */
    public function useStrictTypes()
    {
        $this->useStrict = true;

        return $this;
    }

    /**
     * @return bool
     */
    public function getUseStrictTypes(): bool
    {
        return $this->useStrict;
    }

    /**
     * @return $this
     */
    public function preferDefaultsSetInConstructor()
    {
        $this->preferDefaultsSetInConstructor = true;

        return $this;
    }

    /**
     * @return bool
     */
    public function getPreferDefaultsSetInConstructor(): bool
    {
        return $this->preferDefaultsSetInConstructor;
    }
}
