<?php
declare(strict_types=1);

namespace JDWil\PhpGenny\Builder\Node\Traits;

trait NodeBehaviorTrait
{
    /**
     * @var int
     */
    protected $phpTargetVersion = 70;

    /**
     * @var bool
     */
    protected $autoGenerateDocBlocks;

    /**
     * @return $this
     */
    public function autoGenerateDocBlocks()
    {
        $this->autoGenerateDocBlocks = true;

        return $this;
    }

    /**
     * @param int $version
     */
    public function setPhpTargetVersion(int $version)
    {
        $this->phpTargetVersion = $version;
    }
}
